name: Update MGTron Package to PyPi

on:
  push:
    branches:
      - active_development
    tags:
      - v1.*

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository testpypi dist/*
